#!/bin/sh

: ${PUPPET_MANIFEST:=node.pp}
: ${PUPPET_ENVIRONMENT:=production}
: ${PUPPET_MODULEPATH:=$(puppet config print modulepath --environment $PUPPET_ENVIRONMENT)}

puppet_apply_library () {
	local lib=$1
	local version

	[ -d "$lib" ] || return

	(
	echo "*** running puppet library: $lib"
	cd $lib

	[ -f version ] && version=$(cat version)
	[ -f env ] && . ./env

	puppet apply --verbose \
		${version:+--config_version="echo $version"} \
		--environment $PUPPET_ENVIRONMENT \
		--modulepath $PUPPET_MODULEPATH:$PWD/modules \
		$PUPPET_MANIFEST
	)
}

if [ "${PUPPET_USE_HOSTNAME:-n}" != y ]; then
	export FACTER_fqdn=localhost
fi

# ensure we don't leave a populated yum cache hanging around.
trap "yum clean all" EXIT

echo "*** start running puppet libraries"
cd /puppet
for lib in $(lsdep *); do
	puppet_apply_library $lib || exit 1
done
echo "*** finished running puppet libraries"
